### ISSUE TITLE
Error when remove bookmark

### ISSUE THREAD

**Issue by horosgrisa** [jocelynmallon/zshmarks#22]
Please use `rm` instead of `mv`, https://github.com/jocelynmallon/zshmarks/blob/master/zshmarks.plugin.zsh#L121. When I remove bookmark I obtain following error:
```
/usr/bin/mv: cannot move '/home/grisa/.bookmarks.bak' to '/home/grisa/.Trash/bookmarks12-48-16': No such file or directory
```

**Comment by jocelynmallon** [comment]
I prefer to use mv instead of rm whenever possible because RM is instant/permanent/unsafe. mv allows the user to recover their old bookmarks file if something goes wrong.

Are you using Linux or Cygwin/Windows?

I think this is probably just an issue of different trash/recycle bin locations across OS's?

**Comment by horosgrisa** [comment]
I use Arch Linux, and I don't have ~/.Trash folder.

**Comment by horosgrisa** [comment]
But I think that bookmarks are not important information, and you can delete them without backup.

**Comment by jocelynmallon** [comment]
I don't personally agree about deleting without backup, especially if the user has symlinked the .bookmarks file somewhere else.

But it seems like there is no standard trash location/path across linux distro's, e.g.
    /home/.Trash-0/
    /home/username/.local/share/Trash/files/

For now we can check 'uname' and if we're on Mac, use mv, but rm anywhere else.
